make status enums
TritonSE/OGY-Email-Automation pull request #15
Opened 2020-12-14 22:52 UTC by arnavtaneja

### Administrative Info
Monday Board ID: 853648344
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
- Made file that created status enums

### Testing
How did you confirm your changes worked? 
- I did not. Should work in theory though.

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.
- new file in the migrations folder

| [TODO Screenshot Title] |
| --- |
| [TODO Screenshot Link] |

2020-12-14 22:58 UTC, eliasfang approved these changes
LGTM

2020-12-22 03:16 UTC, ThomasLiARDJAVA commented on app/database/migrations/20201207174436_make_status_enum.js
> +        tbl.string('status');
This is very good, but I did more research to the syntax and the functionalities of this particular method. It is better to use the native enum method from knex and actually handle it that way. 

        `tbl.enum('status', status, {useNative: true, enumName:'status_enum'}).notNullable().index();`
Also you can delete the .then portion of the code.

Sorry for the confusion

2020-12-22 03:16 UTC, ThomasLiARDJAVA requested changes
Change the enum initialization type

2021-01-08 02:09 UTC, ThomasLiARDJAVA commented on app/database/migrations/20201207174436_make_status_enum.js
> +    tbl.enum('status', status, {useNative: true, enumName:'status_enum'}).notNullable().index();
return knex.schema.table('jobs', (tbl) => {

2021-02-06 22:48 UTC, ThomasLiARDJAVA approved these changes

2021-02-06 22:48 UTC, merged