Feature/algorithmist girl/873143574 create middleware verify token
TritonSE/OGY-Email-Automation pull request #21
Opened 2021-01-29 02:32 UTC by Algorithmist-Girl

### Administrative Info
Monday Board ID: 853648344
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- I added the middleware function for verify token.

### Testing
How did you confirm your changes worked? 

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.
![65D04B37-C509-419B-AC4E-D442DFB07FFC_4_5005_c](https://user-images.githubusercontent.com/36552319/106223714-f6a34b80-61af-11eb-9f33-700524a77d1a.jpeg)

2021-01-30 21:13 UTC, ThomasLiARDJAVA requested changes
Good job! For right now, this looks good, and the user interface routers are not being created yet so you don't have to worry about using this anywhere right now. Just take out the unused library, and add the export line.

2021-01-30 21:13 UTC, ThomasLiARDJAVA commented on app/middleware/verifyToken.js
> +const { NotExtended } = require("http-errors");
I feel like this library is not used anywhere right? you can delete it.

2021-01-30 21:13 UTC, ThomasLiARDJAVA commented on app/middleware/verifyToken.js
> +}
Make sure at the end of the file add a line: 
```
module.exports=verifyToken;
```
so we can use this function in other files.

2021-02-05 02:42 UTC, ThomasLiARDJAVA approved these changes
LGTM

2021-02-05 02:49 UTC, eliasfang approved these changes
You might want to fix the merge conflict before you can merge. I'd also recommend adding more description with the changes you made and how you tested it. But other than that, you're good to go!

2021-02-05 03:57 UTC, shravan1k requested changes
It would be great to add JSDoc comments so it is clearer to understand the parameters, such as nextOperation.

2021-02-07 00:26 UTC, shravan1k approved these changes
LGTM

2021-02-10 18:12 UTC, shravan1k requested changes
`.DS_Store` should be removed from this commit before it gets merged.

Regarding testing, how did you confirm that the code works? Is there anyway to test it? 
Also the PR title shouldn't be the branch name.

2021-02-10 18:12 UTC, shravan1k commented on app/middleware/verifyToken.js
> + * @param {} request the request, from which we get the token from
Add the type of the parameters

2021-02-10 18:12 UTC, shravan1k commented on app/middleware/verifyToken.js
> +    // if undefined
Redundant comment, could you clarify more on what undefined means?

2021-02-17 06:23 UTC, shravan1k approved these changes

2021-02-19 02:18 UTC, Algorithmist-Girl commented
Merging middleware function for verify token

2021-02-21 23:01 UTC, merged