Add class end time column
TritonSE/OGY-Email-Automation pull request #38
Opened 2021-03-09 04:43 UTC by NicoleChen08

Add class end time column

### Administrative Info
Monday Board ID: 853648344
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
We added a column to the jobs table that indicates the time the classes end, as well as updated the parser script to get the end time from the API.  

### Testing
How did you confirm your changes worked? 
Visually looked at code, cannot run migration until PR is approved.  

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| [TODO Screenshot Title] |
| --- |
| [TODO Screenshot Link] |

2021-03-09 18:58 UTC, mingkaili approved these changes

2021-03-09 19:39 UTC, shravan1k requested changes
Need to update app/models/jobsModel.js as well to account for the new information being inserted to the database.

2021-03-10 04:12 UTC, shravan1k requested changes
The insert and update jobs function shouldn't be in the migrations file.

2021-03-12 02:12 UTC, shravan1k approved these changes
LGTM!

2021-03-13 22:18 UTC, merged