Create clients list modal
TritonSE/OGY-Email-Automation pull request #46
Opened 2021-04-21 07:45 UTC by shravan1k

### Administrative Info
Monday Board ID: 853648344
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Modified the getAll function in jobsModel to include the list of clients along with each job.
- Added a function in clientsModel to retrieve all of the clients attending a specific class.
- Made clients modal and integrated with the application.

### Testing
How did you confirm your changes worked? 
- Tested the modal separate from the app using HTML.
- Integrated the modal into the app and opened it in browser to confirm that the modal looked fine and correctly reflected information in the database.

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| Clients Modal |
| --- |
| <img width="676" alt="Screen Shot 2021-04-21 at 12 42 33 AM" src="https://user-images.githubusercontent.com/42595673/115515938-79c9c000-a23a-11eb-8577-aba0db476cba.png"> |

2021-04-21 18:20 UTC, eliasfang requested changes
This looks so good! Just a quick note about the images that you're importing. I don't if you knew but materialize actually have icons that I used on mine so I didn't need to import any images. For example, I know that materialize has the notifications icons, the locker icon, and the people icon. But it's up to you if you want to use those instead. You can find them here: https://materializecss.com/icons.html

2021-04-21 18:20 UTC, eliasfang commented on app/public/javascripts/uiheader.js
> +$(document).ready(function () {
I think you can technically just combine these two together right?

2021-04-23 21:30 UTC, ThomasLiARDJAVA requested changes

2021-04-23 21:30 UTC, mingkaili commented on app/views/components/clients.ejs
> +                        <% if(client.is_recipient == true){ %>
You can change this expression to boolean? (<true condition>):(<false condition>)

2021-04-24 19:46 UTC, eliasfang approved these changes
Everything looks great! I just merged my branch to main so just make sure you merge that into yours and make any necessary changes :)

2021-04-25 03:48 UTC, ThomasLiARDJAVA approved these changes

2021-04-25 05:12 UTC, merged