Backend Script Fixes
TritonSE/OGY-Email-Automation pull request #52
Opened 2021-05-10 00:46 UTC by shravan1k

### Administrative Info
Monday Board ID: 853648344
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Check for differences between database and api response before attempting to update jobs.
- Script now sends emails for classes that start in the range of 15 mins to 30 mins after present time.
- No longer inserts jobs from api that are happening within 15 mins from present time.
- Updates statuses of jobs to success or fail after attempt to send reminder emails.

### Testing
How did you confirm your changes worked? 
- To confirm that updates were occurring properly, I modified values in the database and then ran the script. Only the jobs that were changed were being passed into updateJobs and the updates were reflected in the database.
- To confirm that the emails were being sent only once and that the statuses of the jobs were updating properly, I added a client to the database for a job that was happening between 15 and 30 mins. The email only sent once and the database correctly updated.

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

If just an id is printed, it means that the job with the id was passed into updateJobs.

| When job needs to be updated | When job is already up to date |
| --- | --- |
| <img width="483" alt="Screen Shot 2021-05-09 at 11 51 07 AM" src="https://user-images.githubusercontent.com/42595673/117592632-2b4b6b00-b0ee-11eb-81fb-02073e518bb1.png"> | <img width="464" alt="Screen Shot 2021-05-09 at 11 50 11 AM" src="https://user-images.githubusercontent.com/42595673/117592642-330b0f80-b0ee-11eb-9a9c-967d86d9ee52.png"> |

2021-05-10 00:49 UTC, eliasfang approved these changes
Nice!

2021-05-10 22:42 UTC, ThomasLiARDJAVA requested changes

2021-05-10 22:42 UTC, ThomasLiARDJAVA commented on app/models/jobsModel.js
> +async function getByMinutesFromNow(minMinutes, maxMinutes){
rename to getByMinutesInRange

2021-05-10 22:42 UTC, mingkaili commented on app/models/jobsModel.js
> +async function updateJobStatus(jobId, isSuccess){
Usually, we don't pass the condition in as a parameter, the following format is better: 

```
if(isSuccess){
  await jobModel.updateById();
}
```

Also, name this function updateById, you don't need a separate function for updating one single field

2021-05-10 22:42 UTC, mingkaili commented on modules/mailer.js
> +                    jobsModel.updateJobStatus(classInfo.id, false);
name change

2021-05-10 22:42 UTC, mingkaili commented on modules/mailer.js
> +                    jobsModel.updateJobStatus(classInfo.id, true);
name change

2021-05-11 06:56 UTC, ThomasLiARDJAVA approved these changes

2021-05-11 07:14 UTC, merged